### ISSUE TITLE
判断出了有cdn，下一步动作会报错，请问师傅这是什么意思？

### ISSUE THREAD

**Issue by xiaozhaha** [Pluto-123/Bypass_cdn#1]
![image](https://user-images.githubusercontent.com/48639007/118645374-7150af00-b811-11eb-8a63-ca2974241ba4.png)

**Comment by Pluto-123** [comment]
你好，我复现过程没有发现问题，可以把打码的扫描目标发给我吗，邮箱也可以2652998314@qq.com，谢谢~
